#[cfg(feature = "consoleapi")]
pub mod consoleapi;
#[cfg(feature = "d3d11")]
pub mod d3d11;
#[cfg(feature = "d3dcompiler")]
pub mod d3dcompiler;
#[cfg(feature = "fileapi")]
pub mod fileapi;
#[cfg(feature = "handleapi")]
pub mod handleapi;
#[cfg(feature = "ioapiset")]
pub mod ioapiset;
#[cfg(feature = "libloaderapi")]
pub mod libloaderapi;
#[cfg(feature = "memoryapi")]
pub mod memoryapi;
#[cfg(feature = "processthreadsapi")]
pub mod processthreadsapi;
#[cfg(feature = "profileapi")]
pub mod profileapi;
#[cfg(feature = "psapi")]
pub mod psapi;
#[cfg(feature = "securitybaseapi")]
pub mod securitybaseapi;
#[cfg(feature = "synchapi")]
pub mod synchapi;
#[cfg(feature = "sysinfoapi")]
pub mod sysinfoapi;
#[cfg(feature = "timeapi")]
pub mod timeapi;
#[cfg(feature = "tlhelp32")]
pub mod tlhelp32;
#[cfg(feature = "winbase")]
pub mod winbase;
#[cfg(feature = "wincon")]
pub mod wincon;
#[cfg(feature = "wincontypes")]
pub mod wincontypes;
#[cfg(feature = "winnt")]
pub mod winnt;
#[cfg(feature = "winsvc")]
pub mod winsvc;
#[cfg(feature = "winuser")]
pub mod winuser;
#[cfg(feature = "wow64apiset")]
pub mod wow64apiset;
